### ISSUE TITLE
Wrong error message in MustBeEqualsValidationError

### ISSUE THREAD

**Issue by auf1r2** [skarpushin/summerb#9]
MustBeEqualsValidationError generate message: Validation error: values **NULL** and A should be equals.

but should generate:

MustBeEqualsValidationError generate message: Validation error: values **A** and B should be equals.

See superclass constructor call it have unneeded null at 3rd parameter. (MustBeEqualsValidationError:20)

**Comment by auf1r2** [comment]
![123](https://cloud.githubusercontent.com/assets/7643313/7936488/1182e8f6-0942-11e5-9dcb-60eb832f9f0e.png)

Error visualisation

**Comment by skarpushin** [comment]
Bug fixed in 0.0.2-SNAPSHOT
https://github.com/skarpushin/summerb/tree/mvn-repo/org/summerb/summerb/0.0.2-SNAPSHOT
